name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      
      - name: Set up requirements
        run: go get -u github.com/oschwald/geoip2-golang github.com/go-bindata/go-bindata/...

      - name: Check out source code
        uses: actions/checkout@v1
        
      - name: Create assets
        run: go-bindata -nometadata -pkg main -prefix data/ -o bindata.go data/GeoLite2-City.mmdb data/GeoLite2-ASN.mmdb

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .
